<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[STEP1]]>
    </line>
    <line>
      <![CDATA[STEP2]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="89" started-at="2016-09-18T16:45:06Z" finished-at="2016-09-18T16:45:06Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="89" started-at="2016-09-18T16:45:06Z" finished-at="2016-09-18T16:45:06Z">
      <class name="com.automation.main.past_courses.TC17903VerifyTheUI">
        <test-method status="FAIL" signature="setup()[pri:0, instance:com.automation.main.past_courses.TC17903VerifyTheUI@58ceff1]" name="setup" is-config="true" duration-ms="0" started-at="2016-09-18T19:45:06Z" finished-at="2016-09-18T19:45:06Z">
          <exception class="atu.testng.reports.exceptions.ATUReporterStepFailedException">
            <full-stacktrace>
              <![CDATA[[ATU Custom Reporter Step Failed Exception]
	at atu.testng.reports.ATUReports.stepFailureHandler(Unknown Source)
	at atu.testng.reports.ATUReports.add(Unknown Source)
	at com.automation.main.past_courses.TC17903VerifyTheUI.setup(TC17903VerifyTheUI.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- atu.testng.reports.exceptions.ATUReporterStepFailedException -->
          <reporter-output>
            <line>
              <![CDATA[STEP1]]>
            </line>
            <line>
              <![CDATA[STEP2]]>
            </line>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="testUiExistence()[pri:0, instance:com.automation.main.past_courses.TC17903VerifyTheUI@58ceff1]" name="testUiExistence" duration-ms="2" started-at="2016-09-18T19:45:06Z" finished-at="2016-09-18T19:45:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUiExistence -->
        <test-method status="SKIP" signature="closeBroswer()[pri:0, instance:com.automation.main.past_courses.TC17903VerifyTheUI@58ceff1]" name="closeBroswer" is-config="true" duration-ms="0" started-at="2016-09-18T19:45:06Z" finished-at="2016-09-18T19:45:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBroswer -->
      </class> <!-- com.automation.main.past_courses.TC17903VerifyTheUI -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
